DROP TABLE IF EXISTS CLIENT;

CREATE TABLE CLIENT  (
      CLIENT_ID INT AUTO_INCREMENT  PRIMARY KEY , 
      BRANCH_ID SMALLINT , 
      EMPLOYER_ID INTEGER , 
      CATEGORY_ID SMALLINT NOT NULL , 
      FIRST_NAME VARCHAR(50) NOT NULL , 
      MIDDLE_NAME VARCHAR(50) NOT NULL , 
      LAST_NAME VARCHAR(50) NOT NULL , 
      TRANSLIT_NAME VARCHAR(60) , 
      DOB DATE , 
      POB VARCHAR(150) , 
      EMAIL VARCHAR(100) , 
      HAS_EMAIL_SUBSCRIPTION CHAR(1) NOT NULL , 
      LEGAL_ADDRESS VARCHAR(500) , 
      INN VARCHAR(12) , 
      PHONE VARCHAR(50) , 
      MOBILE_PHONE VARCHAR(50) , 
      PASS_SERIE VARCHAR(50) NOT NULL , 
      PASS_NUM VARCHAR(50) NOT NULL , 
      PASS_ISSUER VARCHAR(150) NOT NULL , 
      PASS_DATE DATE NOT NULL , 
      RESIDENT CHAR(1) NOT NULL , 
      LASTMODIFIED TIMESTAMP NOT NULL , 
      REGION_CODE INTEGER , 
      BUNDLE_CODE CHAR(4) , 
      IS_COMPLIANCE DECIMAL(1,0) , 
      IS_PEP DECIMAL(1,0) , 
      CURRENT_ADDRESS VARCHAR(500)
      );

INSERT INTO CLIENT (BRANCH_ID, EMPLOYER_ID, CATEGORY_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, TRANSLIT_NAME, DOB, POB, EMAIL, HAS_EMAIL_SUBSCRIPTION, LEGAL_ADDRESS, INN, PHONE, MOBILE_PHONE,
 PASS_SERIE, PASS_NUM, PASS_ISSUER, PASS_DATE, RESIDENT, LASTMODIFIED, REGION_CODE, BUNDLE_CODE, IS_COMPLIANCE, IS_PEP, CURRENT_ADDRESS) VALUES
(200, null, 60, 'Ivan', 'Ivanovich', 'Petrov', 'Petrov Ivan Ivanych', '1970-01-23', 'Moskow', 'some@mail.ru', 'N', 'address 1', '89777000', '+7-926-000-00-01', '+7-926-000-00-01', 'XXX', 'XXXXXX', 'YYYYYYYYYY',
'2000-05-30', 'Y', '2020-01-30 10:00:00', 77, null, 0, 0, 'current'),
(200, null, 60, 'Petr', 'Spiridonovish', 'Petryshev', 'Pedrichev Petr Spiridonovish', '1990-06-06', 'Moskow', 'some_new@mail.ru', 'N', 'address 2', '89777000', '+7-926-000-00-01', '+7-926-000-00-01', 'XXX', 'XXXXXX', 'YYYYYYYYYY',
'2000-05-30', 'Y', '2020-01-30 10:00:00', 77, null, 0, 0, 'current');

DROP TABLE IF EXISTS PROCURATION;

CREATE TABLE PROCURATION  (
      ATTORNEY_CNUM INT NOT NULL,
      ACTION_ID INT NOT NULL,
      ACCOUNT_ID INT NOT NULL,
      FMA VARCHAR(50) NOT NULL,
      POA_ID INT NOT NULL
      );

DROP TABLE IF EXISTS POA;

CREATE TABLE POA (
      POA_ID INT AUTO_INCREMENT  PRIMARY KEY,
      POA_NUMBER VARCHAR(50),
      POA_TYPE_ID INT,
      BRANCH_REF CHAR(3),
      PRINCIPAL_CNUM INT,
      PRINCIPAL_FIO_RUS VARCHAR(150),
      PRINCIPAL_FIO_ENG VARCHAR(150),
      PRINCIPAL_DOCTYPE VARCHAR(3),
      PRINCIPAL_DOC_SER VARCHAR(50),
      PRINCIPAL_DOC_NUM VARCHAR(50),
      PRINCIPAL_DOC_ISSUEDBY VARCHAR(150),
      PRINCIPAL_DOC_ISSUEDDATE DATE,
      ATTORNEY_PERSON_TYPE_ID INT,
      ATTORNEY_CNUM INT,
      ATTORNEY_FIO_RUS VARCHAR(150),
      ATTORNEY_FIO_ENG VARCHAR(150),
      ATTORNEY_DOCTYPE VARCHAR(3),
      ATTORNEY_DOC_SER VARCHAR(50),
      ATTORNEY_DOC_NUM VARCHAR(50),
      ATTORNEY_DOC_ISSUEDBY VARCHAR(150),
      ATTORNEY_DOC_ISSUEDDATE DATE,
      CREATE_DATE TIMESTAMP,
      START_DATE DATE,
      EXPIRATION_DATE DATE,
      CANCEL_DATE DATE,
      DELETE_DATE TIMESTAMP,
      VALIDITY_PERIOD_Y INT,
      VALIDITY_PERIOD_M INT,
      VALIDITY_PERIOD_D INT,
      STATUS INT,
      LASTMODIFIED TIMESTAMP,
      IS_ATTORNEY_VALID INT
      );
